### PR TITLE
[Userpools] Fix network calls to run in background when specified fixes #668

### LINKED ISSUE #668: RunInBackground flag does not work
Why does runinbackground get network in main thread error on android?
**Which AWS Services are you utilizing?**
AWS Cognito user.initiateUserAuthentication
**Provide code snippets (if applicable)**
    
```
AuthenticationDetails authenticationDetails = new AuthenticationDetails(phoneNumber, new HashMap<String, String>(), new HashMap<String, String>());
                String secretHash = CognitoSecretHash.getSecretHash(phoneNumber, clientId, clientSecret);
                authenticationDetails.setAuthenticationParameter(CognitoServiceConstants.AUTH_PARAM_USERNAME, phoneNumber);
                authenticationDetails.setAuthenticationParameter(CognitoServiceConstants.AUTH_PARAM_SECRET_HASH, secretHash);

        user.initiateUserAuthentication(authenticationDetails, new AuthenticationHandler() {
            @Override
            public void onSuccess(CognitoUserSession userSession, CognitoDevice newDevice) {
                Log.d(TAG, "Success");
            }

            @Override
            public void getAuthenticationDetails(AuthenticationContinuation authenticationContinuation, String userId) {
                Log.d(TAG, "details");
            }

            @Override
            public void getMFACode(MultiFactorAuthenticationContinuation continuation) {
                Log.d(TAG, "mfa");
            }

            @Override
            public void authenticationChallenge(ChallengeContinuation continuation) {
                Intent intent = new Intent(context, LoginSmsActivity.class);
                context.startActivity(intent);
            }

            @Override
            public void onFailure(Exception exception) {
                Log.d(TAG, "Failure");
            }
        }, true).run();
```
**Environment(please complete the following information):**
aws-android-sdk-auth-userpools:2.6.+@aar'

**Device Information (please complete the following information):**
Nexus 6 API 24

### PR DESCRIPTION
**Pull request by minbi**
Also includes minor refactor of request method call structure.

### CODE REVIEW

File: aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java [hunk 1]
```diff
@@ -767,6 +772,26 @@ public void getSession(final AuthenticationHandler callback) {
      */
     public Runnable initiateUserAuthentication(final AuthenticationDetails authenticationDetails,
             final AuthenticationHandler callback, final boolean runInBackground) {
+        final Runnable task = _initiateUserAuthentication(authenticationDetails, callback, runInBackground);
+        if (runInBackground) {
+            return new Runnable() {
+                @Override
+                public void run() {
+                    new Thread(new Runnable() {
```
Comment (joknu1) [inline aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java]: It's very hard to understand what is going on here. Do you have any test cases that cover these changes?

E.g. the changes in this commit makes `getSessionInBackground` call  `AuthenticationHandler#onFailure()` on _background_ thread once user enters (incorrect) username/password and `continueTask()` has been called. `onSuccess()` is still called from _main thread_ however. I would have expected the callbacks to run on main thread, or at least be consistent.

Comment (minbi) [reply aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java]: There is a code fix that will be addressing the issue you have pointed out, the release is pending.

Comment (minbi) [reply aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java]: Generally, this client calls the onSuccess and onFailure cases on the same thread that `foo()` is called. Except when the `fooInBackground()` variant is used, that is when the callbacks are made on the main thread's looper.
