### PR TITLE
Fixes race condition, mfa issue, and need for modifying manifest

### LINKED ISSUE #871: "user cancelled" exception
Describe the bug:

I followed manual setup to Use Amazon Cognito Hosted UI to implement social login. But I got an error "user cancelled".
when I sign out with API AWSMobileClient.getInstance().SignOut() and then  I use your API AWSMobileClient.getInstance().showSignIn(..) to Sign in.
For the first time calls API : it went to facebook/google custom tab (my account signed in facebook/google), it comes back with an error "user cancel" even though i don't close or cancel the chrome. I try to check user state when error"user cancel" by AWSMobileClient.getInstance().addUserStateListener(...): the user state i got is "SIGNED_IN"
But the second times i call that API again it succeeded. 
I realized that the "user cancelled" exception is not only thrown when a user closes/cancels the Chrome tab, but also when the tab becomes hidden after successful authentication.

I solved that problem by the way that i use API AWSMobileClient.getInstance().addUserStateListener(...) although it got an error "user cancel" but if the user state is "SIGNED_IN" i will ignore it error.  But problem i got here The UI is jerky. 

To Reproduce:

```java
** code to sign in **
// For Google
HostedUIOptions hostedUIOptions = HostedUIOptions.builder()
    .scopes("openid", "email")
    .identityProvider("Google")
    .build();

// For Facebook
HostedUIOptions hostedUIOptions = HostedUIOptions.builder()
    .scopes("openid", "email")
    .identityProvider("Facebook")
    .build();

SignInUIOptions signInUIOptions = SignInUIOptions.builder()
    .hostedUIOptions(hostedUIOptions)
    .build();
// 'this' refers to the current active Activity
AWSMobileClient.getInstance().showSignIn(this, signInUIOptions, new Callback<UserStateDetails>() {
    @Override
    public void onResult(UserStateDetails details) {
        Log.d(TAG, "onResult: " + details.getUserState());
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "onError: ", e);
    }
});
**code to check user state **
AWSMobileClient.getInstance().addUserStateListener(new UserStateListener() {
            @Override
            public void onUserStateChanged(UserStateDetails userStateDetails) {
                switch (userStateDetails.getUserState()){
                    case GUEST:
                        Log.i("userState", "user is in guest mode");
                        break;
                    case SIGNED_OUT:
                        Log.i("userState", "user is signed out");
                        break;
                    case SIGNED_IN:
                        requestAuthentication();
                        Log.i("userState", "user is signed in");
                        break;
                    case SIGNED_OUT_USER_POOLS_TOKENS_INVALID:
                        Log.i("userState", "need to login again");
                        break;
                    case SIGNED_OUT_FEDERATED_TOKENS_INVALID:
                        Log.i("userState", "user logged in via federation, but currently needs new tokens");
                        break;
                    default:
                        Log.e("userState", "unsupported");
                }
            }
        });
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: I tried: 2.12.5, 2.12.7, 2.13.0
 - Device: real device: Samsung, Redmi, Xiaomi
 - Android Version: 7.1.1, 8.1.0

I hope you will fix the problem soon. 
Thanks

### PR DESCRIPTION
**Pull request by TrekSoft**
Addresses #871 and #764 by adding intermediate activities to manage the HostedUI flow properly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+import android.content.Intent;
+import android.net.Uri;
+import android.os.Bundle;
+import android.util.Log;
+
+import com.amazonaws.mobileconnectors.cognitoauth.AuthClient;
+
+import java.util.logging.Logger;
+
+public class CustomTabsManagerActivity extends Activity {
```
Comment (raphkim) [inline aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java:14]: If it's not meant to be extended, let's put `final` keyword on it

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+    private Intent customTabsIntent;
+
+    /**
+     * Creates an intent to start an OAuth2 flow in Chrome custom tabs.
+     * @param context the package context for the app.
+     * @param customTabsIntent the intent for the Chrome custom tab.
+     */
+    public static Intent createStartIntent(
+            Context context,
+            Intent customTabsIntent
```
Comment (raphkim) [inline aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java:28]: Can we annotate the the parameters and return values with `@NonNull` and `@Nullable` for every publicly exposed methods?

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java [hunk 3]
```diff
@@ -153,8 +161,10 @@ protected void setUsername(final String username) {
      *     state in the redirect uri to fetch the stored proof-key.
      * </p>
      * @param showSignInIfExpired true if the web UI should launch when the session is expired
+     * @param activity The activity to launch the sign in experience from.
+     *                 This must not be null when showSignInIfExpired is true.
```
Comment (raphkim) [inline aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java:165]: What happens if `activity` is null and `showSignInIfExpired` is true? Is this relationship enforced anywhere?

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java [hunk 4]
```diff
@@ -238,11 +254,16 @@ public void getTokens(final Uri uri) {
...
         getTokens(uri, userHandler);
     }
 
+    /**
+     * Properly handles the event where the user cancels out of the custom tabs auth flow either by closing it
+     * or navigating back away from it.
+     */
+    public void handleCustomTabsCancelled() {
+        userHandler.onFailure(new AuthNavigationException("user cancelled"));
+    }
```
Comment (raphkim) [inline aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java:266]: why does this have to be exposed to the customers? Why do they need to use this method instead of implementing their own callback behavior?

Comment (raphkim) [reply aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java:266]: ^ Same question for `handleFlowCancelled()`

File: gradle.properties [hunk 5]
```diff
@@ -25,7 +25,7 @@ android.useAndroidX=true
 android.enableJetifier=true
 
 GROUP=com.amazonaws
-VERSION_NAME=@SDK_VERSION@
```
Comment (raphkim) [inline gradle.properties:28]: was this an intended change?

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java [hunk 6]
```diff
@@ -554,30 +587,50 @@ private void launchSignOut(final String redirectUri) {
...
-
 	        CustomTabsIntent.Builder builder = new CustomTabsIntent.Builder(mCustomTabsSession);
 	        mCustomTabsIntent = builder.build();
 	        if(pool.getCustomTabExtras() != null)
 	            mCustomTabsIntent.intent.putExtras(pool.getCustomTabExtras());
 	        mCustomTabsIntent.intent.setPackage(ClientConstants.CHROME_PACKAGE);
-	        mCustomTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NO_HISTORY);
-	        mCustomTabsIntent.intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
-	        mCustomTabsIntent.launchUrl(context, uri);
+            mCustomTabsIntent.intent.setData(uri);
```
Comment (TrekSoft) [inline aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java:605]: Bad whitespacing - bad...

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java [hunk 7]
```diff
@@ -0,0 +1,127 @@
...
+    public static Intent createResponseHandlingIntent(Context context, Uri responseUri) {
+        Intent intent = createBaseIntent(context);
+        intent.setData(responseUri);
+        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP);
+        return intent;
+    }
+
+    private static Intent createBaseIntent(Context context) {
+        Intent intent = new Intent(context, CustomTabsManagerActivity.class);
+        return intent;
```
Comment (raphkim) [inline aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java:50]:
```suggestion
        return new Intent(context, CustomTabsManagerActivity.class);
```

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java (hunk 4 above)
Comment (raphkim) [reply aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java:266]: Question resolved in-person

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java (hunk 3 above)
Comment (raphkim) [reply aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java:165]: Question resolved in-person

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/Auth.java [hunk 8]
```diff
@@ -648,30 +649,26 @@ public Bundle getCustomTabExtras() {
...
-     *     authentication code.
+     *     If valid tokens are not available locally or if the username is not set, the error callback
+     *     will be invoked. It will not launch a sign in experience.
      * </p>
      */
-    public void getSession(final boolean launchWebUIIfExpired) {
-        this.user.getSession(launchWebUIIfExpired);
+    public void getSessionWithoutWebUI() {
+        this.user.getSession(false, null);
     }
```
[the remark this answers is not in the document]
Comment (raphkim) [reply aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/Auth.java:672]: Question resolved in-person

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/Auth.java [hunk 9]
```diff
@@ -648,30 +649,26 @@ public Bundle getCustomTabExtras() {
      *     get tokens from the authentication code. <i>Uri</i> is the redirect uri with the
      *     authentication code.
      * </p>
+     * @param activity Activity to launch custom tabs from and which will listen for the intent completions.
      */
-    public void getSession() {
-        this.user.getSession(true);
+    public void getSession(final Activity activity) {
```
[the remark this answers is not in the document]
Comment (raphkim) [reply aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/Auth.java:654]: Question resolved in-person

**Comment by raphkim** [comment]
How is this going to be tested? I know that Jameson made changes to the `minSdk`s to support `uiautomator`. I think this is a big enough change to warrant some tests (in a separate PR for the sake of moving forward).

File: aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java (hunk 2 above)
Comment (raphkim) [reply aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/activities/CustomTabsManagerActivity.java:28]: nit: not worth the efforts in the v2 SDK

**Comment by TrekSoft** [comment]
> How is this going to be tested? I know that Jameson made changes to the `minSdk`s to support `uiautomator`. I think this is a big enough change that warrants some tests (in a separate PR for the sake of moving forward).

We don't currently have tests for HostedUI and would be a fairly significant undertaking to add now so given that Amplify Auth is going to ultimately be the preferred solution going forward, don't think it's worth adding at this point.
