### PR TITLE
Make checking for TransferNetworkLossHandler optional.

### LINKED ISSUE #899: S3 upload hangs up in WAITING_FOR_NETWORK state
**Bug description**
After upgrading the `aws-android-sdk-mobile-client` from `2.12.6` to `2.13.1` the code which uploaded image to S3 against `TransferUtility` stopped working. It was hanging up in `WAITING_FOR_NETWORK` state.

**How To Reproduce**
No special circumstances took place: wi-fi connection with internet was available.
The s3 file upload was initiated with the following code (which worked on aws-sdk `2.13.0` and `2.12.6`)

```
val s3Client = AmazonS3Client(AWSMobileClient.getInstance(), region((context)))
val observer = TransferUtility.builder().s3Client(s3Client)
        .context(context)
        .awsConfiguration(AWSMobileClient.getInstance().configuration)
        .build()
        .upload(bucketName(context), name, file)
observer.setTransferListener(listener)
```

The transfer listener was like this
```
TransferListener {
	override fun onStateChanged(id: Int, state: TransferState?) {
		Log.i(TAG, "Upload state changed to ${state?.name}")
	}
	override fun onError(id: Int, ex: java.lang.Exception) {
		Log.e(TAG, "Failed to upload to S3, job id $jobId", ex)
	}

	override fun onProgressChanged(id: Int, bytesCurrent: Long, bytesTotal: Long) {
		showProgressNotification(bytesCurrent.toInt(), bytesTotal.toInt())
	}
}
```
When upload started, the app received only one `onStateChanged` with `WAITING_FOR_NETWORK` state and no other updates reported to `TransferListener`. File was not uploaded to S3 bucket. 

**Affected AWS service(s)**
S3

**Expected behavior**
File should be uploaded with progress updates reported to `TransferListener`

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: `2.13.1`
 - Devices: `Xiaomi Mi5s` and `Samsung Galaxy J7 (2016)`
 - Android Version: 8.0.0 (Xiaomi) / 8.1.0 (Samsung)

**Additional context**
There was such message in the logs (com.amazonaws.mobileconnectors.s3.transferutility.UploadTask):

```
2019-04-12 17:04:49.831 9610-16011/com.ehawk.repath.staging E/UploadTask: 
TransferUtilityException: [com.amazonaws.mobileconnectors.s3.transferutility.TransferUtilityException: TransferNetworkLossHandler is not created. Please call `TransferNetworkLossHandler.getInstance(Context)` to instantiate it before retrieving]
2019-04-12 17:05:23.249 9610-16011/com.ehawk.repath.staging I/UploadTask: Network not connected. Setting the state to WAITING_FOR_NETWORK.
```
After that `UploadTask.call()` finished and no actual upload happened

Questions:
1. Is it now mandatory to register `TransferNetworkLossHandler` for being able to use `TransferUtility`?
1. Is there any examples of how that should be done? Is `Application.onCreate()` a valid point to create/register this?

### PR DESCRIPTION
**Pull request by kvasukib**
Fixes #899

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/UploadTask.java [hunk 1]
```diff
@@ -88,10 +88,15 @@ public UploadTask(TransferRecord uploadInfo,
      */
     @Override
     public Boolean call() throws Exception {
-        if (!isNetworkHandlerRegisteredAndNetworkConnected()) {
```
Comment (cbommas) [inline aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/UploadTask.java]: The `isNetworkHandlerRegisteredAndNetworkConnected` method is also used in  the `uploadMultipartAndWaitForCompletion` method. It would be good make this change there as well.

Also, once that is done, remove the `isNetworkHandlerRegisteredAndNetworkConnected` method as it will no longer be needed.

Comment (kvasukib) [reply aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/UploadTask.java]: Made the change.
